name: Test getting branch name (release 1)
on: 
  push:
    branches:
      - 'release/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: create pr
        run: |
          echo ${{github.ref_name}} | sed 's/\./\n/g'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
