name: Test getting branch name
on:
  push:
    branches:
      - 'release/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: create pr
        run: |
          echo ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
