name: Test getting branch name (release 1)
on: 
  push:
    branches:
      - 'release/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: split branch name
        id: splitt
        run: |
          echo "split-array=${{ github.ref_name }} | sed 's/\./\n/g'" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create pr
        run: |
          echo ${{join(steps.splitt.outputs.*, '-')}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
