name: Test getting branch name (release 1)
on: 
  push:
    branches:
      - 'release/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: split branch name
        id: splitt
        run: |
          IFS=. read -r v1 v2 v3 <<< "$GITHUB_REF_NAME"    # split into (integer) components
          ((v2++))                                         # do the math
          patch="${v1}.${v2}.${v3}"                        # paste back together
          echo "$(echo $patch)"
        #echo "$(echo $GITHUB_REF_NAME | sed 's/\./\n/g')"
      - name: create prr
        run: |
          echo ${{steps.splitt.outputs.*}}
        #echo ${{join(steps.splitt.outputs.split-array, '-')}}
