name: hello-world
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v9
      - name: my-step
        run: echo "Job fail"
  job-2:
    runs-on: ubuntu-latest
    #if: ${{ failure() }}
    steps:
      - name: my-step
        run: echo "Job error"
