name: hello-world
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: my-step
        run: echo "Job 1 success"
  job-2:
    runs-on: ubuntu-latest
    needs: [ job-1 ]
    steps:
      - uses: actions/checkout@v9
      - name: my-step
        run: echo "Job 2 fail"
  job-3:
    runs-on: ubuntu-latest
    needs: [ job-2 ]
    steps:
      - uses: actions/checkout@v9
      - name: my-step
        run: echo "Job 2 fail"
  job-4:
    runs-on: ubuntu-latest
    needs: [ job-3 ]
    steps:
      - uses: actions/checkout@v2
      - name: my-step
        run: echo "Job 1 success"
  job-5:
    runs-on: ubuntu-latest
    needs: [ job-1, job-2, job-3 ]
    if: ${{ failure() }}
    steps:
      - name: my-step
        run: echo "Job-3 detect job-2 error"
